# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lodjinha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lodjinha
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.5'
  
  target 'LodjinhaTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'LodjinhaUITests' do
    
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
    end
  end
end
